
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://gjqsecsmbbfypwwiiiib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqcXNlY3NtYmJmeXB3d2lpaWliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MDk4NjQsImV4cCI6MjA2NDQ4NTg2NH0.yRsFzt2jljZlh9tEvpbCm9wNJ-eT2J4cGTTbzSdjB1s";

// Define the database types inline since the types file is read-only
export interface Database {
  public: {
    Tables: {
      messages: {
        Row: {
          id: string;
          user_id: string | null;
          name: string;
          email: string;
          phone: string;
          subject: string;
          message_content: string;
          status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          name: string;
          email: string;
          phone: string;
          subject: string;
          message_content: string;
          status?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          name?: string;
          email?: string;
          phone?: string;
          subject?: string;
          message_content?: string;
          status?: string;
          created_at?: string;
        };
      };
      applications: {
        Row: {
          id: string;
          user_id: string;
          application_name: string;
          personal_info: any | null;
          parent_info: any | null;
          academic_info: any | null;
          additional_info: any | null;
          status: string;
          application_date: string;
          reviewed_at: string | null;
          reviewed_by: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          application_name: string;
          personal_info?: any | null;
          parent_info?: any | null;
          academic_info?: any | null;
          additional_info?: any | null;
          status?: string;
          application_date?: string;
          reviewed_at?: string | null;
          reviewed_by?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          application_name?: string;
          personal_info?: any | null;
          parent_info?: any | null;
          academic_info?: any | null;
          additional_info?: any | null;
          status?: string;
          application_date?: string;
          reviewed_at?: string | null;
          reviewed_by?: string | null;
        };
      };
      notifications: {
        Row: {
          id: string;
          user_id: string | null;
          title: string;
          message: string;
          status: string | null;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          title: string;
          message: string;
          status?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          title?: string;
          message?: string;
          status?: string | null;
          created_at?: string | null;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
