// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjqsecsmbbfypwwiiiib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqcXNlY3NtYmJmeXB3d2lpaWliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MDk4NjQsImV4cCI6MjA2NDQ4NTg2NH0.yRsFzt2jljZlh9tEvpbCm9wNJ-eT2J4cGTTbzSdjB1s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);